nelmio_cors:
    defaults:
        allow_origin: ["http://localhost:3000", "http://localhost:3001"]
        allow_credentials: true
        allow_headers: ["Content-Type", "Authorization", "Accept"]
        allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        expose_headers: ["Link", "Authorization"]
        max_age: 3600
    paths:
        "^/api/":
            allow_origin: ["http://localhost:3000", "http://localhost:3001"]
            allow_headers: ["Content-Type", "Authorization", "Accept"]
            allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allow_credentials: true
