name: ${PROJECT_NAME}

services:
  front:
    build:
      context: ../front
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    image: ${FRONT_IMAGE:-mybank/front}:${FRONT_IMAGE_TAG:-latest}
    depends_on: [api]
    ports: ["${FRONT_HTTP_PORT:-80}:80"]
    environment:
      - APP_ENV=${APP_ENV}
    restart: unless-stopped

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    image: ${API_IMAGE:-mybank/api}:${API_IMAGE_TAG:-latest}
    depends_on: [db]
    ports: ["${API_HTTP_PORT:-8000}:8000"]
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?serverVersion=16&charset=utf8
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_PATH:-./data/postgres}:/var/lib/postgresql/data
    restart: unless-stopped
