name: mybank-tests

services:
  db-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: mybank_test
    tmpfs: ["/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d mybank_test"]
      interval: 5s
      timeout: 3s
      retries: 20

  api-test:
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      APP_ENV: test
      DATABASE_URL: postgresql://test:test@db-test:5432/mybank_test?serverVersion=16&charset=utf8
    depends_on:
      db-test:
        condition: service_healthy

    command: ["php", "-S", "0.0.0.0:8000", "-t", "public", "public/index.php"]
