services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"

    App\State\ExpenseProcessor:
        arguments:
            $persistProcessor: "@api_platform.doctrine.orm.state.persist_processor"
