name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # 1) Tests back
      - name: Setup PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: intl, pdo_pgsql

      - name: Install back dependencies
        working-directory: api
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPUnit
        working-directory: api
        run: php ./vendor/bin/phpunit --testdox

      # 2) Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Build & Push API
      - name: Build & Push API image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mybank-api:latest

      # 4) Build & Push Front
      - name: Install front deps & Build
        working-directory: front
        run: |
          npm ci
          npm run build

      - name: Build & Push Front image
        uses: docker/build-push-action@v4
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mybank-front:latest
