name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      # PHP & Composer pour les tests
      - name: Setup PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: intl, pdo_pgsql
          coverage: none

      - name: Install back dependencies
        working-directory: api
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPUnit
        working-directory: api
        run: php ./vendor/bin/phpunit --testdox

      # Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build et push API
      - name: Build & Push API image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mybank-api:latest

      # Build et push Front
      - name: Build & Push Front image
        uses: docker/build-push-action@v4
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mybank-front:latest
