name: CI & CD

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Composer dependencies
        working-directory: api
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHPUnit
        working-directory: api
        run: php bin/phpunit --testdox

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push API image
        uses: docker/build-push-action@v4
        with:
          context: api
          file: api/Dockerfile
          push: true
          tags: zatlou/mybank-api:latest

      - name: Build & push Front image
        uses: docker/build-push-action@v4
        with:
          context: front
          file: front/Dockerfile
          push: true
          tags: zatlou/mybank-front:latest

  deploy-to-vm:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/mybank
            docker pull zatlou/mybank-api:latest
            docker pull zatlou/mybank-front:latest
            docker-compose down
            docker-compose up -d --build
