name: CI & CD

on:
  push:
    branches: [main]

jobs:
  build-test:
    # votre job existant : tests + build & push image

  deploy-to-vm:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Pull & restart services on VM
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ~/mybank
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            docker-compose pull
            docker-compose up -d
          EOF
