name: CD

on:
  push:
    branches: [main]
   pull_request:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    needs: build-and-publish # s’appuie sur le job CI précédent
    environment: production # optionnel, pour GitHub Environments

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SSH key & known_hosts
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            cd /home/deploy/mybank
            docker-compose pull
            docker-compose up -d
          EOF
